
package br.com.curso.webservices.cliente;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ContatoWService", targetNamespace = "http://webservices.curso.com.br/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ContatoWService {


    /**
     * 
     * @param cpf
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "inserirCpf", targetNamespace = "http://webservices.curso.com.br/", className = "br.com.curso.webservices.cliente.InserirCpf")
    @ResponseWrapper(localName = "inserirCpfResponse", targetNamespace = "http://webservices.curso.com.br/", className = "br.com.curso.webservices.cliente.InserirCpfResponse")
    @Action(input = "http://webservices.curso.com.br/ContatoWService/inserirCpfRequest", output = "http://webservices.curso.com.br/ContatoWService/inserirCpfResponse")
    public String inserirCpf(
        @WebParam(name = "cpf", targetNamespace = "")
        String cpf);

    /**
     * 
     * @param cpf
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "excluirCpf", targetNamespace = "http://webservices.curso.com.br/", className = "br.com.curso.webservices.cliente.ExcluirCpf")
    @ResponseWrapper(localName = "excluirCpfResponse", targetNamespace = "http://webservices.curso.com.br/", className = "br.com.curso.webservices.cliente.ExcluirCpfResponse")
    @Action(input = "http://webservices.curso.com.br/ContatoWService/excluirCpfRequest", output = "http://webservices.curso.com.br/ContatoWService/excluirCpfResponse")
    public String excluirCpf(
        @WebParam(name = "cpf", targetNamespace = "")
        String cpf);

    /**
     * 
     * @param cpf
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "procuraCpf", targetNamespace = "http://webservices.curso.com.br/", className = "br.com.curso.webservices.cliente.ProcuraCpf")
    @ResponseWrapper(localName = "procuraCpfResponse", targetNamespace = "http://webservices.curso.com.br/", className = "br.com.curso.webservices.cliente.ProcuraCpfResponse")
    @Action(input = "http://webservices.curso.com.br/ContatoWService/procuraCpfRequest", output = "http://webservices.curso.com.br/ContatoWService/procuraCpfResponse")
    public String procuraCpf(
        @WebParam(name = "cpf", targetNamespace = "")
        String cpf);

}
