
package br.com.curso.webservices.cliente;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ContatoWServiceService", targetNamespace = "http://webservices.curso.com.br/", wsdlLocation = "http://localhost:8000/ContatoWService?wsdl")
public class ContatoWServiceService
    extends Service
{

    private final static URL CONTATOWSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException CONTATOWSERVICESERVICE_EXCEPTION;
    private final static QName CONTATOWSERVICESERVICE_QNAME = new QName("http://webservices.curso.com.br/", "ContatoWServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8000/ContatoWService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CONTATOWSERVICESERVICE_WSDL_LOCATION = url;
        CONTATOWSERVICESERVICE_EXCEPTION = e;
    }

    public ContatoWServiceService() {
        super(__getWsdlLocation(), CONTATOWSERVICESERVICE_QNAME);
    }

    public ContatoWServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CONTATOWSERVICESERVICE_QNAME, features);
    }

    public ContatoWServiceService(URL wsdlLocation) {
        super(wsdlLocation, CONTATOWSERVICESERVICE_QNAME);
    }

    public ContatoWServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CONTATOWSERVICESERVICE_QNAME, features);
    }

    public ContatoWServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ContatoWServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ContatoWService
     */
    @WebEndpoint(name = "ContatoWServicePort")
    public ContatoWService getContatoWServicePort() {
        return super.getPort(new QName("http://webservices.curso.com.br/", "ContatoWServicePort"), ContatoWService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ContatoWService
     */
    @WebEndpoint(name = "ContatoWServicePort")
    public ContatoWService getContatoWServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservices.curso.com.br/", "ContatoWServicePort"), ContatoWService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CONTATOWSERVICESERVICE_EXCEPTION!= null) {
            throw CONTATOWSERVICESERVICE_EXCEPTION;
        }
        return CONTATOWSERVICESERVICE_WSDL_LOCATION;
    }

}
